"use strict";

const CAPABILITY_CONTRACT_VERSION = "1.0.0";

const CAPABILITY_OUTCOME_STATE = Object.freeze({
  COMPLETE: "COMPLETE",
  PARTIAL: "PARTIAL",
  NO_DATA: "NO_DATA",
  INCONCLUSIVE: "INCONCLUSIVE",
  UNSUPPORTED: "UNSUPPORTED",
  UNAVAILABLE: "UNAVAILABLE",
  FAILED: "FAILED",
});

const CANDIDATE_FACT_TYPE = Object.freeze({
  RELATIONSHIP: "RELATIONSHIP",
  ENTITY_ATTRIBUTE: "ENTITY_ATTRIBUTE",
});

const RELATIONSHIP_TYPE = Object.freeze({
  ECONOMIC_OWNERSHIP: "ECONOMIC_OWNERSHIP",
  VOTING_RIGHTS: "VOTING_RIGHTS",
  BOARD_APPOINTMENT_RIGHT: "BOARD_APPOINTMENT_RIGHT",
  BOARD_REMOVAL_RIGHT: "BOARD_REMOVAL_RIGHT",
  FORMAL_CONTROL_RIGHT: "FORMAL_CONTROL_RIGHT",
  SIGNIFICANT_INFLUENCE_OR_CONTROL: "SIGNIFICANT_INFLUENCE_OR_CONTROL",
  TRUST_OWNERSHIP: "TRUST_OWNERSHIP",
  SETTLOR: "SETTLOR",
  TRUSTEE: "TRUSTEE",
  PROTECTOR: "PROTECTOR",
  BENEFICIARY: "BENEFICIARY",
  CONTROL_OVER_TRUST_OR_INTERMEDIARY: "CONTROL_OVER_TRUST_OR_INTERMEDIARY",
});

const PERCENTAGE_VALUE_TYPE = Object.freeze({
  EXACT: "EXACT",
  RANGE: "RANGE",
  UNKNOWN: "UNKNOWN",
});

const IDENTITY_RESOLUTION_STATUS = Object.freeze({
  RESOLVED: "RESOLVED",
  UNRESOLVED: "UNRESOLVED",
  REJECTED: "REJECTED",
});

module.exports = {
  CAPABILITY_CONTRACT_VERSION,
  CAPABILITY_OUTCOME_STATE,
  CANDIDATE_FACT_TYPE,
  RELATIONSHIP_TYPE,
  PERCENTAGE_VALUE_TYPE,
  IDENTITY_RESOLUTION_STATUS,
};
