"use strict";

const CAPABILITY_CONTRACT_VERSION = "1.0.0";

const POLICY_PACK_SCHEMA_ID = "ubo-policy-pack";
const POLICY_PACK_SCHEMA_VERSION = "1.0";
const CONDITION_LANGUAGE_VERSION = "ubo-condition-v1";
const REQUIREMENT_STATE_MODEL_VERSION = "ubo-requirement-state-v1";
const CLAIM_STATE_MODEL_VERSION = "ubo-claim-state-v1";
const APPLICABILITY_MODEL_VERSION = "ubo-applicability-v1";
const RESOLUTION_SEMANTICS_VERSION = "ubo-resolution-v1";
const RISK_LEVEL_MODEL_VERSION = "ubo-risk-level-v1";

const CAPABILITY_OUTCOME_STATE = Object.freeze({
  COMPLETE: "COMPLETE",
  PARTIAL: "PARTIAL",
  NO_DATA: "NO_DATA",
  INCONCLUSIVE: "INCONCLUSIVE",
  UNSUPPORTED: "UNSUPPORTED",
  UNAVAILABLE: "UNAVAILABLE",
  FAILED: "FAILED",
});

const CANDIDATE_FACT_TYPE = Object.freeze({
  RELATIONSHIP: "RELATIONSHIP",
  ENTITY_ATTRIBUTE: "ENTITY_ATTRIBUTE",
});

const RELATIONSHIP_TYPE = Object.freeze({
  ECONOMIC_OWNERSHIP: "ECONOMIC_OWNERSHIP",
  VOTING_RIGHTS: "VOTING_RIGHTS",
  BOARD_APPOINTMENT_RIGHT: "BOARD_APPOINTMENT_RIGHT",
  BOARD_REMOVAL_RIGHT: "BOARD_REMOVAL_RIGHT",
  FORMAL_CONTROL_RIGHT: "FORMAL_CONTROL_RIGHT",
  SIGNIFICANT_INFLUENCE_OR_CONTROL: "SIGNIFICANT_INFLUENCE_OR_CONTROL",
  TRUST_OWNERSHIP: "TRUST_OWNERSHIP",
  SETTLOR: "SETTLOR",
  TRUSTEE: "TRUSTEE",
  PROTECTOR: "PROTECTOR",
  BENEFICIARY: "BENEFICIARY",
  CONTROL_OVER_TRUST_OR_INTERMEDIARY: "CONTROL_OVER_TRUST_OR_INTERMEDIARY",
});

const PERCENTAGE_VALUE_TYPE = Object.freeze({
  EXACT: "EXACT",
  RANGE: "RANGE",
  UNKNOWN: "UNKNOWN",
});

const IDENTITY_RESOLUTION_STATUS = Object.freeze({
  RESOLVED: "RESOLVED",
  UNRESOLVED: "UNRESOLVED",
  REJECTED: "REJECTED",
});

const REQUIREMENT_STATE = Object.freeze({
  UNRESOLVED: "UNRESOLVED",
  RESOLVED: "RESOLVED",
  GAP: "GAP",
  CONFLICT: "CONFLICT",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
  N_A: "N_A",
});

const CLAIM_STATE = Object.freeze({
  CANDIDATE: "CANDIDATE",
  OPERATIVE: "OPERATIVE",
  PROVISIONAL: "PROVISIONAL",
  DISPUTED: "DISPUTED",
  SUPERSEDED: "SUPERSEDED",
  REJECTED: "REJECTED",
});

const APPLICABILITY_RESULT = Object.freeze({
  APPLIES: "APPLIES",
  DOES_NOT_APPLY: "DOES_NOT_APPLY",
  UNKNOWN: "UNKNOWN",
});

const RESOLUTION_STRATEGY = Object.freeze({
  DISCOVERY: "DISCOVERY",
  EXISTING_EVIDENCE: "EXISTING_EVIDENCE",
  CUSTOMER_DOCUMENT: "CUSTOMER_DOCUMENT",
  CUSTOMER_QUESTION: "CUSTOMER_QUESTION",
  CUSTOMER_ATTESTATION: "CUSTOMER_ATTESTATION",
  DETERMINISTIC_CALCULATION: "DETERMINISTIC_CALCULATION",
  ANALYST_REVIEW: "ANALYST_REVIEW",
});

const RESOLUTION_EFFECT = Object.freeze({
  POSITIVE_ONLY: "POSITIVE_ONLY",
  POSITIVE_OR_NEGATIVE: "POSITIVE_OR_NEGATIVE",
  CORROBORATIVE_ONLY: "CORROBORATIVE_ONLY",
  CALCULATION_ONLY: "CALCULATION_ONLY",
});

const RISK_LEVEL = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
});

module.exports = {
  APPLICABILITY_MODEL_VERSION,
  APPLICABILITY_RESULT,
  CAPABILITY_CONTRACT_VERSION,
  CAPABILITY_OUTCOME_STATE,
  CANDIDATE_FACT_TYPE,
  CLAIM_STATE,
  CLAIM_STATE_MODEL_VERSION,
  CONDITION_LANGUAGE_VERSION,
  IDENTITY_RESOLUTION_STATUS,
  PERCENTAGE_VALUE_TYPE,
  POLICY_PACK_SCHEMA_ID,
  POLICY_PACK_SCHEMA_VERSION,
  RELATIONSHIP_TYPE,
  REQUIREMENT_STATE,
  REQUIREMENT_STATE_MODEL_VERSION,
  RESOLUTION_EFFECT,
  RESOLUTION_SEMANTICS_VERSION,
  RESOLUTION_STRATEGY,
  RISK_LEVEL,
  RISK_LEVEL_MODEL_VERSION,
};
