"use strict";
const {MemoryA4aRepository}=require("./repository"); const {EvidenceNeedEvaluationService}=require("./service"); const {FixtureNeedEvaluationProvider}=require("./providers");
const tenantId="nium",contextId="a4a00000-0000-4000-8000-000000000001";
const needs=[{id:"a4a10000-0000-4000-8000-000000000001",tenantId,contextId,schemaReference:"fixture:kyb",schemaFieldId:"company_number",requirementId:"requirement-id"},{id:"a4a10000-0000-4000-8000-000000000002",tenantId,contextId,schemaReference:"fixture:kyb",schemaFieldId:"business_name",requirementId:"requirement-name"}];
function fact(n,concept,value,extra={}){return{id:`a4a20000-0000-4000-8000-${String(n).padStart(12,"0")}`,tenantId,extractionRunId:`run-${n}`,artifactId:`artifact-${n}`,semanticConceptId:concept,factValue:value,requestStatus:extra.requestStatus||"requested",groundingType:extra.groundingType||"direct",supportState:extra.supportState||"supported",createdAt:"2026-08-19T10:00:00.000Z",capturedAt:"2026-08-18T10:00:00.000Z"};}
async function buildFixtureDemonstration(){const facts=[fact(1,"company_number","00445790"),fact(2,"business_name","TESCO PLC"),fact(3,"registered_company_name","Tesco Plc",{requestStatus:"discovered"}),fact(4,"company_number","99999999"),fact(5,"business_name","Tesco Plc"),fact(6,"business_name","TESCO PLC",{supportState:"needs_verification"}),fact(7,"registered_company_name","Tesco Plc",{requestStatus:"discovered"}),fact(8,"officer_name",["A","B"]),fact(9,"officer_name",[]),fact(10,"business_name","Tesco Plc",{groundingType:"derived"})];const repository=new MemoryA4aRepository({needs,facts});const service=new EvidenceNeedEvaluationService({repository,semanticProvider:new FixtureNeedEvaluationProvider(),providerLineage:{provider:"fixture",model:"fixture-v1",instructionReference:"evidence-a4a-semantic-fixture-v1"}});const scenarios=[];async function run(name,args,note){const bundle=await service.evaluate({tenantId,contextId,...args});scenarios.push({name,note,run:bundle.run,evaluations:bundle.evaluations,a3Support:args.factIds.map(id=>facts.find(f=>f.id===id)?.supportState),evidenceCompleteness:name.includes("collection")?"explicitly bounded; no cardinality conclusion":"not evaluated",downstreamKycDecision:"not performed"});}
await run("Exact typed company identifier",{informationNeedId:needs[0].id,factIds:[facts[0].id],method:"exact_typed",comparisonInput:{value:"00445790",valueType:"string",identifierScheme:"companies_house"},evaluationContext:{factIdentifierScheme:"companies_house"}});
await run("Conservatively normalized company name",{informationNeedId:needs[1].id,factIds:[facts[1].id],method:"normalized_text",comparisonInput:{value:"Tesco Plc"}});
await run("Semantic discovered company name",{informationNeedId:needs[1].id,factIds:[facts[2].id],method:"semantic"});
await run("Identifier mismatch",{informationNeedId:needs[0].id,factIds:[facts[3].id],method:"exact_typed",comparisonInput:{value:"00445790"}});
await run("Two candidates; no winner",{informationNeedId:needs[1].id,factIds:[facts[1].id,facts[4].id],method:"normalized_text",comparisonInput:{value:"Tesco Plc"}},"Independent results; no winner selected.");
await run("A3 needs_verification can address",{informationNeedId:needs[1].id,factIds:[facts[5].id],method:"normalized_text",comparisonInput:{value:"Tesco Plc"}});
await run("Discovered Fact remains discovered",{informationNeedId:needs[1].id,factIds:[facts[6].id],method:"semantic"});
await run("Collection boundary",{informationNeedId:needs[1].id,factIds:[facts[7].id],method:"semantic"},"No completeness or cardinality inference.");
await run("Legitimate empty versus unavailable",{informationNeedId:needs[1].id,factIds:[facts[8].id],method:"semantic"},"Empty collection is preserved as a value; unavailable is a run failure, not a conclusion.");
await run("Append-only re-evaluation",{informationNeedId:needs[1].id,factIds:[facts[9].id],method:"semantic"},"A second immutable run; prior run remains.");await run("Append-only re-evaluation (later)",{informationNeedId:needs[1].id,factIds:[facts[9].id],method:"semantic"});
return{stage:"A4a",fixture:true,scenarios,history:repository.bundles.map(x=>x.run),factsUnchanged:facts,finalKycSatisfactionPerformed:false,winnerSelected:false};}
module.exports={buildFixtureDemonstration};
