"use strict";
const crypto=require("node:crypto");
const { NORMALIZATION,normalizeText }=require("./normalization");
const { METHODS,validateEvaluationBundle }=require("./domain");
function id(){return crypto.randomUUID();} function now(){return new Date().toISOString();}
function snapshotNeed(n){return {id:n.id,schemaReference:n.schemaReference||n.schema_reference,schemaVersionReference:n.schemaVersionReference||n.schema_version_reference||null,schemaFieldId:n.schemaFieldId||n.schema_field_id,requirementId:n.requirementId||n.requirement_id};}
function snapshotFact(f){return {id:f.id,extractionRunId:f.extractionRunId,artifactId:f.artifactId,semanticConceptId:f.semanticConceptId,factValue:f.factValue,requestStatus:f.requestStatus,groundingType:f.groundingType,supportState:f.supportState,createdAt:f.createdAt,capturedAt:f.capturedAt,extractionStartedAt:f.extractionStartedAt||null,extractionCompletedAt:f.extractionCompletedAt||null};}
function automaticMethod(need,facts,comparisonInput){const concept=need.schemaFieldId||need.schema_field_id,same=facts.map(f=>f.semanticConceptId===concept);if(same.every(v=>!v))return{method:"normalized_text",reason:"Selected Facts concern concepts unrelated to the Information Need; deterministic concept mismatch is sufficient.",semanticCall:false};if(!comparisonInput||comparisonInput.value===undefined)return{method:"semantic",reason:"The persisted Information Need contains no comparison target, so value comparison is unavailable and semantic relationship evaluation is required.",semanticCall:true};if(same.every(Boolean)&&facts.every(f=>typeof f.factValue===typeof comparisonInput.value&&Object.is(f.factValue,comparisonInput.value)))return{method:"exact_typed",reason:"Fact and explicit comparison target have identical typed values.",semanticCall:false};if(facts.every(f=>typeof f.factValue==="string")&&typeof comparisonInput.value==="string")return{method:"normalized_text",reason:"String values require only conservative versioned normalization.",semanticCall:false};return{method:"semantic",reason:"Typed or normalized deterministic comparison cannot safely resolve the selected relationship.",semanticCall:true};}
class EvidenceNeedEvaluationService {
 constructor({repository,semanticProvider=null,providerLineage={}}){this.repository=repository;this.semanticProvider=semanticProvider;this.providerLineage=providerLineage;}
 async evaluate({informationNeedId,factIds,tenantId,contextId=null,method="automatic",comparisonInput=null,evaluationContext={}}){
 if(!informationNeedId||!Array.isArray(factIds)||!factIds.length)throw Object.assign(new Error("An existing Information Need and at least one existing Fact are required"),{statusCode:400});
  if(method!=="automatic"&&!METHODS.includes(method))throw Object.assign(new Error("Unsupported evaluation method"),{statusCode:400});
  const resolved=await this.repository.resolveInputs({informationNeedId,factIds,tenantId,contextId}); if(!resolved.need)throw Object.assign(new Error("Information Need is not accessible in this context"),{statusCode:404}); if(resolved.facts.length!==new Set(factIds).size)throw Object.assign(new Error("Every selected Fact must exist, belong to the same subject, and be accessible in this context"),{statusCode:403});
  const requestedMethod=method,routing=method==="automatic"?automaticMethod(resolved.need,resolved.facts,comparisonInput):{method,reason:"Reviewer explicitly selected an advanced evaluation method.",semanticCall:method==="semantic"};method=routing.method;
  const started=now(),runId=id(),base={id:runId,informationNeedId,evaluationMethod:method,evaluatorName:method==="semantic"?"semantic-need-evaluator":"deterministic-need-evaluator",evaluatorVersion:"a4a-v1",provider:method==="semantic"?this.providerLineage.provider||null:null,modelIdentifier:method==="semantic"?this.providerLineage.model||null:null,instructionReference:method==="semantic"?this.providerLineage.instructionReference||"evidence-a4a-semantic-v1":method==="normalized_text"?NORMALIZATION.reference:"evidence:a4a/exact-typed-v1",evaluationContext:{...evaluationContext,comparisonInput:comparisonInput||null,requestedMethod,automaticRouting:requestedMethod==="automatic"?routing:null,selectedFactIds:factIds.slice()},startedAt:started,limitations:[],createdAt:started};
  try { const evaluations=[],runLimitations=[]; for(const fact of resolved.facts){let conclusion,normalization={};const sameConcept=fact.semanticConceptId===(resolved.need.schemaFieldId||resolved.need.schema_field_id); if(method==="semantic"){if(!this.semanticProvider)throw Object.assign(new Error("Semantic evaluation provider is not configured"),{code:"provider_not_configured"}); conclusion=await this.semanticProvider.evaluate({fact:snapshotFact(fact),need:snapshotNeed(resolved.need),comparisonInput,context:evaluationContext});runLimitations.push(...(conclusion.limitations||[]));} else if(!sameConcept){conclusion={result:"does_not_address",reason:"The Fact concerns a different schema concept from the Information Need.",qualification:{conceptMismatch:true}};} else if(!comparisonInput||comparisonInput.value===undefined){conclusion={result:"insufficient",reason:"No explicit comparison value was supplied.",qualification:{missingComparisonInput:true}};} else if(method==="exact_typed"){const typed=typeof fact.factValue===typeof comparisonInput.value;const schemeOk=!comparisonInput.identifierScheme||comparisonInput.identifierScheme===evaluationContext.factIdentifierScheme;conclusion={result:typed&&schemeOk&&Object.is(fact.factValue,comparisonInput.value)?"addresses":"does_not_address",reason:typed&&schemeOk&&Object.is(fact.factValue,comparisonInput.value)?"The typed identifier value exactly matches the explicit comparison input.":"The typed value or identifier scheme does not exactly match the explicit comparison input.",qualification:{typed,identifierSchemeCompared:!!comparisonInput.identifierScheme}};} else {const left=normalizeText(fact.factValue),right=normalizeText(comparisonInput.value);normalization={normalizationId:NORMALIZATION.id,normalizationVersion:NORMALIZATION.version,normalizationReference:NORMALIZATION.reference};conclusion={result:left&&left===right?"addresses":"does_not_address",reason:left&&left===right?"Values match under conservative whitespace, case, and Unicode normalization.":"Values do not match under conservative normalization.",qualification:{normalizedFact:left,normalizedComparison:right}};}
    evaluations.push({id:id(),evaluationRunId:runId,factId:fact.id,result:conclusion.result,reason:conclusion.reason,qualification:conclusion.qualification||{},comparisonInputs:{need:snapshotNeed(resolved.need),fact:snapshotFact(fact),explicitComparison:comparisonInput||null},...normalization,createdAt:now()}); }
    const completed=now(),bundle=validateEvaluationBundle({run:{...base,status:"completed",completedAt:completed,evaluatedAt:completed,limitations:[...new Set(runLimitations)]},evaluations});await this.repository.appendEvaluation(bundle);return bundle;
  }catch(error){const failed=now(),bundle=validateEvaluationBundle({run:{...base,status:"failed",completedAt:failed,evaluatedAt:null,errorCode:error.code||"evaluation_failed",errorMessage:error.message,limitations:[]},evaluations:[]});await this.repository.appendEvaluation(bundle);error.details={runId};throw error;}
 }
 async history(args){const selected=new Set(args.factIds||[]),all=await this.repository.listEvaluations(args),runs=selected.size?all.map(run=>{const evaluations=(run.evaluations||[]).filter(item=>selected.has(item.factId||item.fact_id));return{...run,evaluations};}).filter(run=>run.evaluations.length||((run.evaluationContext||run.evaluation_context)?.selectedFactIds||[]).some(id=>selected.has(id))):all;return {informationNeedId:args.informationNeedId,runs,providerCall:false};}
 async selectionOptions({collectionId,tenantId}){if(!collectionId)throw Object.assign(new Error("A loaded Evidence collection is required"),{statusCode:400});const options=await this.repository.listSelectionOptions({collectionId,tenantId});if(!options)throw Object.assign(new Error("The Evidence collection is not accessible in this tenant"),{statusCode:404});return{...options,externalSourceCall:false,aiCall:false,writesPerformed:false};}
}
module.exports={EvidenceNeedEvaluationService,automaticMethod,snapshotFact,snapshotNeed};
