"use strict";

const crypto=require("node:crypto");
const {COMPARATOR,compareCandidates}=require("./comparators");
const {validateAssessmentBundle,validateSpecification}=require("./domain");
function uuid(){return crypto.randomUUID();}function now(){return new Date().toISOString();}
function unique(values){return[...new Set(values.filter(Boolean))];}
function candidateRole(result){return{addresses:"covering",partially_addresses:"partial",does_not_address:"non_covering",ambiguous:"indeterminate",insufficient:"indeterminate"}[result]||"indeterminate";}
function eligibility(spec,candidates){const context=spec.candidateEligibilityContext;if(!context?.required)return{eligible:candidates,sufficient:true,reasons:[]};const decisions=new Map((context.decisions||[]).map((x)=>[x.evaluationId||x.factId,x]));const missing=candidates.filter((c)=>!decisions.has(c.evaluation.id)&&!decisions.has(c.id));return{eligible:candidates.filter((c)=>{const decision=decisions.get(c.evaluation.id)||decisions.get(c.id);return decision?.eligible===true;}),sufficient:missing.length===0,reasons:missing.length?["source_freshness_eligibility_context_required"]:[]};}
function coverageOutcome(candidates,inputSufficient){if(!inputSufficient)return"indeterminate";const values=candidates.map((c)=>c.evaluation.result);if(values.includes("addresses"))return"covered";if(values.includes("partially_addresses"))return"partially_covered";if(values.length&&values.every((x)=>x==="does_not_address"))return"uncovered";return"indeterminate";}
function temporalOutcome(spec,candidates){if(spec.temporalScope==="any")return"not_applicable";const states=candidates.map((c)=>c.typedRelationship?.temporalState||c.typedSetAssertion?.temporalState||"unknown");if(!states.length||states.every((x)=>x==="unknown"))return"indeterminate";if(spec.temporalScope==="current"){const applicable=states.filter((x)=>x==="current").length;if(applicable===states.length)return"applicable";if(applicable)return"partially_applicable";return states.includes("unknown")?"indeterminate":"not_applicable";}if(spec.temporalScope==="historical"){const applicable=states.filter((x)=>["historical","ceased"].includes(x)).length;if(applicable===states.length)return"applicable";if(applicable)return"partially_applicable";return states.includes("unknown")?"indeterminate":"not_applicable";}const point=Date.parse(spec.asOf);let yes=0,unknown=0;for(const c of candidates){const item=c.typedRelationship||c.typedSetAssertion;if(!item){unknown++;continue;}const from=item.effectiveFrom?Date.parse(item.effectiveFrom):-Infinity,to=item.effectiveTo?Date.parse(item.effectiveTo):Infinity;if(point>=from&&point<=to)yes++;else if(item.temporalState==="unknown"&&!item.effectiveFrom&&!item.effectiveTo)unknown++;}return yes===candidates.length?"applicable":yes?"partially_applicable":unknown?"indeterminate":"not_applicable";}
function collectionOutcomes(spec,candidates){if(spec.needShape!=="collection")return{completenessState:"not_applicable",emptySetState:"not_applicable",reasons:[]};const assertions=candidates.map((c)=>c.typedSetAssertion).filter(Boolean);const complete=assertions.find((x)=>x.completenessState==="complete"),empty=assertions.find((x)=>x.emptyState==="established_empty"&&x.completenessState==="complete"),nonEmpty=assertions.find((x)=>x.emptyState==="non_empty");let completenessState=spec.collection.completenessRequirement==="none"?"not_applicable":complete?"complete":assertions.some((x)=>x.completenessState==="incomplete")?"incomplete":"indeterminate";let emptySetState=empty?"established_empty":nonEmpty?"not_established":assertions.length?"indeterminate":"indeterminate";const reasons=[];if(spec.collection.completenessRequirement==="complete_set"&&!complete)reasons.push("completeness_evidence_missing");
  const explicitCount=complete?.explicitMemberCount??assertions.find((x)=>x.explicitMemberCount!=null)?.explicitMemberCount??null,observedCount=candidates.filter((x)=>x.typedRelationship&&["addresses","partially_addresses"].includes(x.evaluation.result)).length,card=spec.collection.cardinality;if(card&&(card.exact!==null||card.minimum!==null||card.maximum!==null)){const minimumEstablished=card.minimum===null||explicitCount!==null&&explicitCount>=card.minimum||observedCount>=card.minimum;const closedCount=complete?explicitCount:null;if(!minimumEstablished){if(complete&&closedCount!==null){completenessState="incomplete";reasons.push("cardinality_not_met");}else reasons.push("cardinality_evidence_missing");}if(card.exact!==null||card.maximum!==null){if(closedCount===null){reasons.push("cardinality_evidence_missing");if(completenessState==="complete")completenessState="indeterminate";}else if((card.exact!==null&&closedCount!==card.exact)||(card.maximum!==null&&closedCount>card.maximum)){completenessState="incomplete";reasons.push("cardinality_not_met");}}}
  return{completenessState,emptySetState,reasons};}

class EvidenceCoverageAssessmentService{
 constructor({repository}){this.repository=repository;}
 async assess({informationNeedId,candidates,specification,tenantId,contextId=null}){
  if(!informationNeedId||!Array.isArray(candidates)||!candidates.length)throw Object.assign(new Error("An Information Need and explicit A4a evaluation/Fact candidates are required"),{statusCode:400});
  for(const item of candidates)if(!item?.evaluationId||!item?.factId)throw Object.assign(new Error("Each candidate requires an explicit A4a evaluation ID and corresponding Fact ID"),{statusCode:400});
  const spec=validateSpecification(specification),resolved=await this.repository.resolveAssessmentInputs({informationNeedId,candidates,tenantId,contextId});if(!resolved.need)throw Object.assign(new Error("Information Need is not accessible in this context"),{statusCode:404});if(resolved.resolvedCandidates.length!==candidates.length)throw Object.assign(new Error("Every explicit A4a evaluation must belong to this Information Need, correspond to the supplied Fact, and be accessible"),{statusCode:403});
  const eligibilityResult=eligibility(spec,resolved.resolvedCandidates),eligible=eligibilityResult.eligible,runId=uuid(),at=now(),findings=[];let comparisonInsufficient=false;
  for(let i=0;i<eligible.length;i++)for(let j=i+1;j<eligible.length;j++){const compared=compareCandidates(eligible[i],eligible[j],spec);if(compared.reasonCode==="identity_association_missing")comparisonInsufficient=true;findings.push({id:uuid(),assessmentRunId:runId,evaluationAId:eligible[i].evaluation.id,factAId:eligible[i].id,evaluationBId:eligible[j].evaluation.id,factBId:eligible[j].id,comparatorId:COMPARATOR.id,comparatorVersion:COMPARATOR.version,comparable:compared.comparable,relationship:compared.relationship,reasonCode:compared.reasonCode,comparisonBasis:{expectedValueShape:spec.expectedValueShape,temporalOutcome:compared.temporalOutcome,association:compared.association||null,basis:compared.basis||null},createdAt:at});}
  const inputSufficient=eligibilityResult.sufficient&&!comparisonInsufficient,collection=collectionOutcomes(spec,eligible);let disagreementState="not_applicable";if(findings.length)disagreementState=findings.some((x)=>x.relationship==="disagrees")?"present":findings.some((x)=>x.relationship==="indeterminate")?"indeterminate":"none";
  const reasonCodes=unique([...eligibilityResult.reasons,...collection.reasons,...findings.filter((x)=>x.relationship==="indeterminate").map((x)=>x.reasonCode)]),run={id:runId,informationNeedId,specificationVersion:spec.specificationVersion,specificationSnapshot:spec,comparatorProfile:spec.comparisonProfile.name,comparatorVersion:spec.comparisonProfile.version,assessedAt:at,coverageState:coverageOutcome(eligible,inputSufficient),completenessState:collection.completenessState,disagreementState,temporalState:temporalOutcome(spec,eligible),emptySetState:collection.emptySetState,inputSufficiency:inputSufficient?"sufficient":"insufficient",reasonCodes,limitations:[],createdAt:at};
  const candidateRows=resolved.resolvedCandidates.map((item)=>({id:uuid(),assessmentRunId:runId,a4aEvaluationId:item.evaluation.id,factId:item.id,contributionRole:item.typedSetAssertion?"set_assertion":candidateRole(item.evaluation.result),evaluationResult:item.evaluation.result,reasonCodes:item===eligible.find((x)=>x.id===item.id)?[]:["candidate_ineligible_under_supplied_context"],createdAt:at}));
  const bundle=validateAssessmentBundle({run,candidates:candidateRows,findings});await this.repository.appendAssessment(bundle);return{...bundle,need:resolved.need,candidateDetails:resolved.resolvedCandidates,noWinnerSelected:true,operativeValue:null,downstreamKycUboDecision:"not_performed",providerCall:false,a4aRerun:false};
 }
 async history(args){if(!args.informationNeedId)throw Object.assign(new Error("Information Need is required"),{statusCode:400});return{informationNeedId:args.informationNeedId,runs:await this.repository.listAssessments(args),assessmentPerformed:false,a4aRerun:false,providerCall:false};}
 async options(args){const result=await this.repository.listAssessmentOptions(args);if(!result)throw Object.assign(new Error("Information Need is not accessible"),{statusCode:404});return{...result,assessmentPerformed:false,a4aRerun:false,providerCall:false};}
}

module.exports={EvidenceCoverageAssessmentService,candidateRole,collectionOutcomes,coverageOutcome,eligibility,temporalOutcome};
