"use strict";
const { randomUUID } = require("node:crypto");

const rows = (r) => r?.rows || r || [];
function mapResult(row) { if (!row) return null; return { collectionId:row.collection_id, idempotencyKey:row.producer_request_key, status:row.collection_status, requestFingerprint:row.request_fingerprint, acquisitionId:row.acquisition_id, assetId:row.asset_id, artifactId:row.artifact_id, subjectReferenceId:row.subject_reference_id, subjectDisplayName:row.display_name, tenantId:row.tenant_id, contextId:row.context_id, originalFilename:row.original_name, mediaType:row.media_type, sizeBytes:Number(row.size_bytes), fingerprintValue:row.fingerprint_value, capturedAt:row.captured_at, sourceEffectiveDate:row.artifact_metadata?.sourceEffectiveDate||null, accessClass:row.access_class, storageProvider:row.storage_provider, storageKey:row.storage_key, storageReference:row.storage_reference }; }

class PostgresR1Repository {
  constructor(db) { this.db=db; }
  async listContexts(tenantId) { const r=await this.db.query(`SELECT c.id, c.context_type, c.external_context_reference, c.subject_reference_id, c.created_at, s.display_name, s.identifier_scheme, s.identifier_value, s.jurisdiction FROM evidence_contexts c JOIN evidence_subject_references s ON s.id=c.subject_reference_id WHERE c.tenant_id=$1 ORDER BY c.created_at DESC`,[tenantId]); return rows(r); }
  async authorizeContext(tenantId, contextId) { const r=await this.db.query(`SELECT c.id, c.tenant_id, c.subject_reference_id, c.context_type, c.external_context_reference, s.display_name, s.identifier_scheme, s.identifier_value, s.jurisdiction FROM evidence_contexts c JOIN evidence_subject_references s ON s.id=c.subject_reference_id WHERE c.id=$1 AND c.tenant_id=$2`,[contextId,tenantId]); return rows(r)[0]||null; }
  async findByKey(key) { const r=await this.db.query(`SELECT co.id collection_id,co.producer_request_key,co.status collection_status,co.producer_metadata->>'requestFingerprint' request_fingerprint,ac.id acquisition_id,a.id asset_id,ar.id artifact_id,co.subject_reference_id,s.display_name,ac.tenant_id,ac.context_id,ar.original_name,ar.media_type,ar.size_bytes,ar.fingerprint_value,ar.captured_at,ar.artifact_metadata,a.access_class,ar.storage_provider,ar.storage_key,ar.storage_reference FROM evidence_collection_operations co LEFT JOIN evidence_acquisitions ac ON ac.collection_operation_id=co.id LEFT JOIN evidence_assets a ON a.acquisition_id=ac.id LEFT JOIN evidence_artifacts ar ON ar.asset_id=a.id LEFT JOIN evidence_subject_references s ON s.id=co.subject_reference_id WHERE co.producer='private_artifact_ingestion' AND co.producer_request_key=$1`,[key]); return mapResult(rows(r)[0]); }
  async createOperation(data) { const id=randomUUID(); const r=await this.db.query(`INSERT INTO evidence_collection_operations(id,producer,producer_request_key,subject_reference_id,collection_coordinates,mode,status,started_at,producer_metadata) VALUES($1,'private_artifact_ingestion',$2,$3,$4::jsonb,'live','running',$5,$6::jsonb) ON CONFLICT(producer,producer_request_key) DO NOTHING RETURNING id`,[id,data.idempotencyKey,data.subjectReferenceId,JSON.stringify({contextId:data.contextId}),data.startedAt,JSON.stringify({requestFingerprint:data.requestFingerprint})]); return rows(r).length ? {id,created:true} : {created:false}; }
  async resumeOperation(id,startedAt){await this.db.query(`UPDATE evidence_collection_operations SET status='running',started_at=$2,completed_at=NULL,failure_reason=NULL WHERE id=$1 AND status='failed'`,[id,startedAt]);return{id,created:true};}
  async complete(data) { return this.db.transaction(async tx=>{ await tx.query(`INSERT INTO evidence_acquisitions(id,context_id,tenant_id,subject_reference_id,source_type,source_provider,acquisition_method,actor_type,actor_id,outcome,source_locator,started_at,completed_at,producer_metadata,collection_operation_id) VALUES($1,$2,$3,$4,'private_upload',NULL,'authorized_host_upload',$5,$6,'successful',$7,$8,$8,$9::jsonb,$10)`,[data.acquisitionId,data.contextId,data.tenantId,data.subjectReferenceId,data.actorType,data.actorId,data.sourceLocator,data.capturedAt,JSON.stringify({sourceChannel:data.sourceChannel}),data.collectionId]); await tx.query(`INSERT INTO evidence_assets(id,acquisition_id,subject_reference_id,evidence_type,title,access_class,observed_at,created_at) VALUES($1,$2,$3,'private_uploaded_artifact',$4,'context_restricted',$5,$5)`,[data.assetId,data.acquisitionId,data.subjectReferenceId,data.title,data.capturedAt]); await tx.query(`INSERT INTO evidence_asset_access_scopes(asset_id,tenant_id,context_id,created_at) VALUES($1,$2,$3,$4)`,[data.assetId,data.tenantId,data.contextId,data.capturedAt]); await tx.query(`INSERT INTO evidence_artifacts(id,asset_id,representation_type,media_type,original_name,storage_provider,storage_key,storage_reference,size_bytes,fingerprint_algorithm,fingerprint_value,captured_at,artifact_metadata,created_at) VALUES($1,$2,'original_upload',$3,$4,$5,$6,$7,$8,'sha256',$9,$10,$11::jsonb,$10)`,[data.artifactId,data.assetId,data.mediaType,data.originalFilename,data.storage.provider,data.storage.key,data.storage.reference,data.sizeBytes,data.fingerprintValue,data.capturedAt,JSON.stringify({sourceEffectiveDate:data.sourceEffectiveDate||null})]); await tx.query(`UPDATE evidence_collection_operations SET status='successful',completed_at=$2 WHERE id=$1`,[data.collectionId,data.capturedAt]); }); }
  async fail(collectionId, reason) { try { await this.db.query(`UPDATE evidence_collection_operations SET status='failed',completed_at=NOW(),failure_reason=$2 WHERE id=$1`,[collectionId,reason]); } catch(_){} }
  async findForReopen({artifactId,tenantId,contextId}) { const r=await this.db.query(`SELECT co.id collection_id,co.producer_request_key,co.status collection_status,co.producer_metadata->>'requestFingerprint' request_fingerprint,ac.id acquisition_id,a.id asset_id,ar.id artifact_id,a.subject_reference_id,s.display_name,ac.tenant_id,ac.context_id,ar.original_name,ar.media_type,ar.size_bytes,ar.fingerprint_value,ar.captured_at,ar.artifact_metadata,a.access_class,ar.storage_provider,ar.storage_key,ar.storage_reference,(a.access_class='public' OR ($3::uuid IS NOT NULL AND ac.tenant_id=$2 AND ac.context_id=$3 AND EXISTS(SELECT 1 FROM evidence_asset_access_scopes scope WHERE scope.asset_id=a.id AND scope.tenant_id=$2 AND scope.context_id=$3))) authorized FROM evidence_artifacts ar JOIN evidence_assets a ON a.id=ar.asset_id JOIN evidence_acquisitions ac ON ac.id=a.acquisition_id LEFT JOIN evidence_collection_operations co ON co.id=ac.collection_operation_id JOIN evidence_subject_references s ON s.id=a.subject_reference_id WHERE ar.id=$1`,[artifactId,tenantId,contextId]); const row=rows(r)[0]; return row ? {...mapResult(row),authorized:!!row.authorized}:null; }
}

class MemoryR1Repository {
  constructor(contexts=[]) { this.contexts=contexts; this.operations=new Map(); this.writes=0; this.failPersistence=false; }
  async listContexts(tenantId){return this.contexts.filter(x=>x.tenant_id===tenantId);}
  async authorizeContext(t,c){return this.contexts.find(x=>x.tenant_id===t&&x.id===c)||null;}
  async findByKey(k){return this.operations.get(k)||null;}
  async createOperation(d){if(this.operations.has(d.idempotencyKey))return{created:false};const v={collectionId:randomUUID(),idempotencyKey:d.idempotencyKey,status:'running',requestFingerprint:d.requestFingerprint,subjectReferenceId:d.subjectReferenceId,tenantId:d.tenantId,contextId:d.contextId};this.operations.set(d.idempotencyKey,v);this.writes++;return{id:v.collectionId,created:true};}
  async resumeOperation(id){for(const [k,v] of this.operations)if(v.collectionId===id){this.operations.set(k,{...v,status:'running',failureReason:null});return{id,created:true};}return{created:false};}
  async complete(d){if(this.failPersistence)throw new Error('database down');const v={...this.operations.get(d.idempotencyKey),...d,status:'successful',storageProvider:d.storage.provider,storageKey:d.storage.key,storageReference:d.storage.reference};this.operations.set(d.idempotencyKey,v);this.writes++;}
  async fail(id,reason){for(const [k,v] of this.operations)if(v.collectionId===id)this.operations.set(k,{...v,status:'failed',failureReason:reason});}
  async findForReopen({artifactId,tenantId,contextId}){const v=[...this.operations.values()].find(x=>x.artifactId===artifactId);return v?{...v,authorized:v.accessClass==='public'||(v.tenantId===tenantId&&v.contextId===contextId)}:null;}
}
module.exports={PostgresR1Repository,MemoryR1Repository};
