"use strict";
const {randomUUID}=require("node:crypto");const {validateInput,requestFingerprint,sha256,R1Error}=require("./domain");
function safeResult(value,replay=false){const {storage,storageKey,storageReference,...safe}=value;return{...safe,idempotentReplay:replay};}
class PrivateArtifactIngestionService{
 constructor({repository,artifactStore,now=()=>new Date().toISOString(),id=()=>randomUUID(),maxBytes=Number(process.env.EVIDENCE_R1_MAX_BYTES)||10*1024*1024}){this.repository=repository;this.store=artifactStore;this.now=now;this.id=id;this.maxBytes=maxBytes;}
 async ingest(raw){const i=validateInput(raw,this.maxBytes);const context=await this.repository.authorizeContext(i.authorizedTenantId,i.authorizedContextId);if(!context)throw new R1Error('access_denied','The authorized tenant cannot use this Evidence context',403);if(i.subjectReferenceId&&i.subjectReferenceId!==context.subject_reference_id)throw new R1Error('access_denied','Subject does not match the authorized Evidence context',403);const fingerprint=requestFingerprint(i,context.subject_reference_id);let existing=await this.repository.findByKey(i.idempotencyKey);if(existing){if(existing.requestFingerprint!==fingerprint)throw new R1Error('idempotency_conflict','Idempotency key was already used for different ingestion input',409);if(existing.status==='successful')return safeResult(existing,true);if(existing.status==='running')throw new R1Error('ingestion_in_progress','This ingestion operation is already running',409);}
 const startedAt=this.now();const created=existing?.status==='failed'?await this.repository.resumeOperation(existing.collectionId,startedAt):await this.repository.createOperation({idempotencyKey:i.idempotencyKey,subjectReferenceId:context.subject_reference_id,contextId:i.authorizedContextId,tenantId:i.authorizedTenantId,requestFingerprint:fingerprint,startedAt});if(!created.created){existing=await this.repository.findByKey(i.idempotencyKey);if(existing?.requestFingerprint!==fingerprint)throw new R1Error('idempotency_conflict','Idempotency key was already used for different ingestion input',409);if(existing?.status==='successful')return safeResult(existing,true);throw new R1Error('ingestion_in_progress','This ingestion operation is already running',409);}
 const ids={collectionId:created.id,acquisitionId:this.id(),assetId:this.id(),artifactId:this.id()};const key=`private/${ids.collectionId}/${ids.artifactId}.${i.media.extension}`;let stored;
 try{stored=await this.store.put(key,i.bytes,i.mediaType);}catch(e){await this.repository.fail(ids.collectionId,'artifact_storage_failed');throw new R1Error('artifact_storage_failed','Private Artifact storage failed',503);}
 try{const read=await this.store.read(stored.key);if(read.bytes.length!==i.bytes.length||sha256(read.bytes)!==i.contentSha256)throw new R1Error('artifact_integrity_mismatch','Stored Artifact failed SHA-256 readback verification',500);const capturedAt=this.now();const data={...ids,idempotencyKey:i.idempotencyKey,requestFingerprint:fingerprint,tenantId:i.authorizedTenantId,contextId:i.authorizedContextId,subjectReferenceId:context.subject_reference_id,subjectDisplayName:context.display_name,actorType:i.actorType,actorId:i.actorId||null,sourceChannel:i.sourceChannel,sourceLocator:i.sourceLocator||null,mediaType:i.mediaType,originalFilename:i.originalFilename,title:i.originalFilename||'Private uploaded artifact',sizeBytes:i.bytes.length,fingerprintValue:i.contentSha256,capturedAt,sourceEffectiveDate:i.sourceEffectiveDate||null,accessClass:'context_restricted',storage:stored};await this.repository.complete(data);return safeResult({...data,storageProvider:stored.provider,status:'successful'});}catch(e){if(this.store.delete)await this.store.delete(stored.key).catch(()=>{});await this.repository.fail(ids.collectionId,e.code||'evidence_persistence_failed');if(e instanceof R1Error)throw e;throw new R1Error('evidence_persistence_failed','Evidence records could not be persisted',503);}
 }
 async reopen({artifactId,authorizedTenantId,authorizedContextId}){if(!artifactId||!authorizedTenantId)throw new R1Error('invalid_request','Artifact ID and authorized tenant are required');const item=await this.repository.findForReopen({artifactId,tenantId:authorizedTenantId,contextId:authorizedContextId||null});if(!item)throw new R1Error('invalid_request','Artifact was not found',404);if(!item.authorized)throw new R1Error('access_denied','Artifact is not authorized for this tenant and context',403);let read;try{read=await this.store.read(item.storageKey);}catch(_){throw new R1Error('artifact_storage_failed','Artifact could not be reopened',503);}const calculated=sha256(read.bytes);if(read.bytes.length!==item.sizeBytes||calculated!==item.fingerprintValue)throw new R1Error('artifact_integrity_mismatch','Reopened Artifact failed SHA-256 verification',500);return{...item,storageKey:undefined,storageReference:undefined,bytes:Buffer.from(read.bytes),integrity:{verified:true,calculatedSha256:calculated}};}
}
module.exports={PrivateArtifactIngestionService};
