"use strict";

const PROVIDERS = Object.freeze({ DIDIT: "DIDIT", VERIFF: "VERIFF" });

const CAPABILITY_STATES = Object.freeze({
  SUPPORTED: "SUPPORTED",
  NOT_SUPPORTED: "NOT_SUPPORTED",
  NOT_CONFIGURED: "NOT_CONFIGURED",
  NOT_AVAILABLE_FOR_DOCUMENT: "NOT_AVAILABLE_FOR_DOCUMENT",
  NOT_REQUESTED: "NOT_REQUESTED",
  EXECUTED: "EXECUTED",
  UNKNOWN: "UNKNOWN",
});

const CANONICAL_STATUSES = Object.freeze({
  CREATED: "CREATED",
  READY: "READY",
  STARTED: "STARTED",
  PROCESSING: "PROCESSING",
  REQUIRES_RETRY: "REQUIRES_RETRY",
  VERIFIED: "VERIFIED",
  FAILED: "FAILED",
  ABANDONED: "ABANDONED",
  EXPIRED: "EXPIRED",
  ERROR: "ERROR",
});

const TERMINAL_STATUSES = Object.freeze(new Set([
  CANONICAL_STATUSES.VERIFIED,
  CANONICAL_STATUSES.FAILED,
  CANONICAL_STATUSES.ABANDONED,
  CANONICAL_STATUSES.EXPIRED,
]));

const OBSERVATION_TYPES = Object.freeze({
  DOCUMENT_AUTHENTICITY: "DOCUMENT_AUTHENTICITY",
  DOCUMENT_VALIDITY: "DOCUMENT_VALIDITY",
  LIVENESS: "LIVENESS",
  FACE_MATCH: "FACE_MATCH",
  NFC_VERIFICATION: "NFC_VERIFICATION",
  DATABASE_VERIFICATION: "DATABASE_VERIFICATION",
});

const OBSERVATION_STATUSES = Object.freeze({
  PASSED: "PASSED",
  FAILED: "FAILED",
  REVIEW: "REVIEW",
  RETRY: "RETRY",
  NOT_PERFORMED: "NOT_PERFORMED",
  UNKNOWN: "UNKNOWN",
});

const CUSTOMER_RESPONSE_ACTIONS = Object.freeze({
  CONFIRMED: "CONFIRMED",
  CORRECTED: "CORRECTED",
  REJECTED: "REJECTED",
});

const LIFECYCLE_EVENTS = Object.freeze({
  IDV_SESSION_CREATED: "IDV_SESSION_CREATED",
  HOSTED_FLOW_OPENED: "HOSTED_FLOW_OPENED",
  DOCUMENT_CAPTURE_STARTED: "DOCUMENT_CAPTURE_STARTED",
  DOCUMENT_SUBMITTED: "DOCUMENT_SUBMITTED",
  DOCUMENT_RETRY_REQUESTED: "DOCUMENT_RETRY_REQUESTED",
  EXTRACTION_AVAILABLE: "EXTRACTION_AVAILABLE",
  DOCUMENT_VERIFICATION_COMPLETED: "DOCUMENT_VERIFICATION_COMPLETED",
  SELFIE_CAPTURE_STARTED: "SELFIE_CAPTURE_STARTED",
  SELFIE_SUBMITTED: "SELFIE_SUBMITTED",
  LIVENESS_COMPLETED: "LIVENESS_COMPLETED",
  FACE_MATCH_COMPLETED: "FACE_MATCH_COMPLETED",
  DATABASE_VERIFICATION_COMPLETED: "DATABASE_VERIFICATION_COMPLETED",
  PROVIDER_DECISION_RECEIVED: "PROVIDER_DECISION_RECEIVED",
  PROVIDER_RESULT_RECEIVED: "PROVIDER_RESULT_RECEIVED",
  CUSTOMER_RETURNED: "CUSTOMER_RETURNED",
  IDV_COMPLETED: "IDV_COMPLETED",
  IDV_ABANDONED: "IDV_ABANDONED",
  IDV_TECHNICAL_FAILURE: "IDV_TECHNICAL_FAILURE",
  IDV_TERMINAL: "IDV_TERMINAL",
  RESUBMISSION_REQUESTED: "RESUBMISSION_REQUESTED",
  IDENTITY_ATTRIBUTE_PRESENTED: "IDENTITY_ATTRIBUTE_PRESENTED",
  IDENTITY_ATTRIBUTE_CONFIRMED: "IDENTITY_ATTRIBUTE_CONFIRMED",
  IDENTITY_ATTRIBUTE_CORRECTED: "IDENTITY_ATTRIBUTE_CORRECTED",
  IDENTITY_ATTRIBUTE_REJECTED: "IDENTITY_ATTRIBUTE_REJECTED",
});

module.exports = {
  PROVIDERS,
  CAPABILITY_STATES,
  CANONICAL_STATUSES,
  TERMINAL_STATUSES,
  OBSERVATION_TYPES,
  OBSERVATION_STATUSES,
  CUSTOMER_RESPONSE_ACTIONS,
  LIFECYCLE_EVENTS,
};
