"use strict";

const AVAILABILITY_RULES_VERSION = "evidence-a5a-availability-v1";
const AVAILABILITY_RULES = Object.freeze({
  requirement_and_need:"created_at, except A2 collection-transaction children are bounded by their linked Collection completion",
  collection_operation:"start is visible at started_at; terminal status, failure and output are visible only at completed_at",
  acquisition:"completed_at, additionally bounded by parent Collection completion",
  evidence_asset_and_artifact:"successful Acquisition completion, additionally bounded by parent Collection completion",
  extraction_run:"completed_at, additionally bounded by input Artifact availability",
  fact_support_locator_relationship_derivation_and_verification:"the relevant Extraction/Interpretation Run completion",
  interpretation_operation:"start is visible at started_at; terminal status, failure and result are visible only at completed_at",
  fact_need_evaluation:"evaluation-run completed_at",
  coverage_assessment:"the later of assessed_at and immutable row created_at",
});
const LIMITATIONS = Object.freeze([
  "Intermediate operation state transitions were not retained; only reconstructable persisted boundaries are shown.",
  "Earlier failed retry attempts may have been overwritten by operation retry state.",
  "Historical Evidence Requirement status changes were not retained.",
  "Historical access-scope revocation state was not retained; current authorization is enforced.",
  "Historical integrity-check executions are not comprehensively retained.",
  "Invalid requests that created no Evidence record cannot be reconstructed.",
  "Downstream KYC/UBO decisions are not reconstructed unless separately integrated.",
]);

function instant(value, field) {
  const date = value instanceof Date ? value : new Date(value);
  if (!value || Number.isNaN(date.getTime())) throw Object.assign(new Error(`${field} must be a valid date/time`), { code: "invalid_as_of" });
  return date;
}
function iso(value) { return value ? new Date(value).toISOString() : null; }
function atOrBefore(value, cutoff) { return !!value && new Date(value).getTime() <= cutoff.getTime(); }
function latest(...values) { const usable=values.filter(Boolean).map((value)=>new Date(value)); return usable.length?new Date(Math.max(...usable.map((value)=>value.getTime()))).toISOString():null; }
function entry({ category,event,occurredAt,availableAt,recordType,id,summary,status=null,contextId=null,subjectReferenceId=null,details={},limitations=[] }) { return {category,event,occurredAt:iso(occurredAt||availableAt),availableAt:iso(availableAt),sourceRecordType:recordType,evidenceReference:{type:recordType,id},summary,status,contextId,subjectReferenceId,details,limitations}; }
function byId(items) { return new Map((items||[]).map((item)=>[item.id,item])); }
function factValue(value) { try{return typeof value==="string"?value:JSON.stringify(value);}catch(_){return "[structured value]";} }
function name(snapshot) { return snapshot?.displayName||snapshot?.name||snapshot?.identifier||snapshot?.reference||"party"; }
function sameInstant(left,right){return !!left&&!!right&&new Date(left).getTime()===new Date(right).getTime();}

function projectEvidence(records, asOf) {
  const cutoff=instant(asOf,"asOf"),entries=[],collections=byId(records.collections),acquisitions=byId(records.acquisitions),assets=byId(records.assets),facts=byId(records.facts),requirements=byId(records.requirements);
  const operationAvailability=new Map(),acquisitionAvailability=new Map(),artifactAvailability=new Map(),runAvailability=new Map(),evaluationAvailability=new Map(),assessmentAvailability=new Map();

  const requirementAvailability=new Map();
  for(const requirement of records.requirements||[]){let availableAt=iso(requirement.createdAt);const linked=(records.requirementAssets||[]).filter((link)=>link.requirementId===requirement.id).map((link)=>assets.get(link.assetId)).filter(Boolean).map((asset)=>acquisitions.get(asset.acquisitionId)).filter(Boolean).map((acquisition)=>collections.get(acquisition.collectionOperationId)).filter((collection)=>collection&&sameInstant(requirement.createdAt,collection.startedAt));if(linked.length){if(linked.some((collection)=>!collection.completedAt)){requirementAvailability.set(requirement.id,null);continue;}availableAt=latest(requirement.createdAt,...linked.map((collection)=>collection.completedAt));}requirementAvailability.set(requirement.id,availableAt);if(atOrBefore(availableAt,cutoff))entries.push(entry({category:"requirement",event:"requirement_recorded",occurredAt:requirement.createdAt,availableAt,recordType:"evidence_requirement",id:requirement.id,summary:`Requirement recorded: ${requirement.description}`,status:requirement.status,contextId:requirement.contextId,subjectReferenceId:requirement.subjectReferenceId,details:{requirementKey:requirement.requirementKey},limitations:["The displayed status is current; historical status transitions were not retained."]}));}
  for(const need of records.needs||[]){const parent=requirements.get(need.requirementId),parentAvailable=parent&&requirementAvailability.get(parent.id);if(parent&&requirementAvailability.has(parent.id)&&!parentAvailable)continue;const availableAt=latest(need.createdAt,parentAvailable);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"information_need",event:"information_need_recorded",occurredAt:need.createdAt,availableAt,recordType:"evidence_information_need",id:need.id,summary:`Information Need recorded: ${need.schemaFieldId}`,contextId:need.contextId,subjectReferenceId:need.subjectReferenceId,details:{schemaReference:need.schemaReference,schemaVersionReference:need.schemaVersionReference,schemaFieldId:need.schemaFieldId}}));}
  for(const operation of records.collections||[]){if(!atOrBefore(operation.startedAt,cutoff))continue;const complete=operation.completedAt&&atOrBefore(operation.completedAt,cutoff),availableAt=complete?operation.completedAt:operation.startedAt;operationAvailability.set(operation.id,complete?iso(operation.completedAt):null);entries.push(entry({category:"collection",event:complete?"collection_completed":"collection_started",occurredAt:operation.startedAt,availableAt,recordType:"evidence_collection_operation",id:operation.id,summary:complete?`${operation.producer} collection ${operation.status}`:`${operation.producer} collection in progress`,status:complete?operation.status:"in_progress",contextId:operation.contextId,subjectReferenceId:operation.subjectReferenceId,details:{producer:operation.producer,mode:operation.mode,collectionCoordinates:operation.collectionCoordinates,completedAt:complete?iso(operation.completedAt):null,failureReason:complete?operation.failureReason:null},limitations:complete?[]:["Intermediate transitions are not retained; later terminal output is intentionally hidden at this cutoff."]}));}
  for(const acquisition of records.acquisitions||[]){const collectionDone=acquisition.collectionOperationId?operationAvailability.get(acquisition.collectionOperationId):null;if(acquisition.collectionOperationId&&collections.has(acquisition.collectionOperationId)&&!collectionDone)continue;const availableAt=latest(acquisition.completedAt,collectionDone);if(!availableAt||!atOrBefore(availableAt,cutoff))continue;acquisitionAvailability.set(acquisition.id,availableAt);entries.push(entry({category:"acquisition",event:"acquisition_completed",occurredAt:acquisition.startedAt,availableAt,recordType:"evidence_acquisition",id:acquisition.id,summary:`${acquisition.sourceProvider||acquisition.sourceType} acquisition ${acquisition.outcome}`,status:acquisition.outcome,contextId:acquisition.contextId,subjectReferenceId:acquisition.subjectReferenceId,details:{collectionOperationId:acquisition.collectionOperationId,sourceType:acquisition.sourceType,sourceProvider:acquisition.sourceProvider,acquisitionMethod:acquisition.acquisitionMethod,completedAt:iso(acquisition.completedAt),outcomeReason:acquisition.outcomeReason,sourceLocator:acquisition.sourceLocator}}));}
  for(const asset of records.assets||[]){const acquisition=acquisitions.get(asset.acquisitionId),availableAt=acquisitionAvailability.get(asset.acquisitionId);if(!availableAt||acquisition?.outcome!=="successful"||!atOrBefore(availableAt,cutoff))continue;entries.push(entry({category:"asset",event:"evidence_asset_available",occurredAt:asset.observedAt,availableAt,recordType:"evidence_asset",id:asset.id,summary:`Evidence Asset available: ${asset.title}`,status:"available",contextId:acquisition.contextId,subjectReferenceId:asset.subjectReferenceId,details:{evidenceType:asset.evidenceType,accessClass:asset.accessClass,acquisitionId:asset.acquisitionId}}));}
  for(const artifact of records.artifacts||[]){const asset=assets.get(artifact.assetId),acquisition=asset&&acquisitions.get(asset.acquisitionId),availableAt=asset&&acquisitionAvailability.get(asset.acquisitionId);if(!availableAt||acquisition?.outcome!=="successful"||!atOrBefore(availableAt,cutoff))continue;artifactAvailability.set(artifact.id,availableAt);entries.push(entry({category:"artifact",event:"artifact_preserved",occurredAt:artifact.capturedAt,availableAt,recordType:"evidence_artifact",id:artifact.id,summary:`Artifact preserved: ${artifact.originalName||artifact.representationType}`,status:"available",contextId:acquisition.contextId,subjectReferenceId:asset.subjectReferenceId,details:{assetId:artifact.assetId,representationType:artifact.representationType,mediaType:artifact.mediaType,originalName:artifact.originalName,sizeBytes:artifact.sizeBytes,sha256:artifact.fingerprintValue,capturedAt:iso(artifact.capturedAt),sourceEffectiveDate:artifact.artifactMetadata?.sourceEffectiveDate||null}}));}
  for(const link of records.requirementAssets||[]){const asset=assets.get(link.assetId),acquisition=asset&&acquisitions.get(asset.acquisitionId),collection=acquisition&&collections.get(acquisition.collectionOperationId),availableAt=latest(link.associatedAt,acquisition?.completedAt,collection?.completedAt);if(acquisition?.outcome==="successful"&&availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"lineage",event:"requirement_asset_associated",occurredAt:link.associatedAt,availableAt,recordType:"evidence_requirement_asset",id:`${link.requirementId}:${link.assetId}:${link.associatedContextId}`,summary:"Evidence Asset associated with Requirement",status:"recorded",contextId:link.associatedContextId,details:{requirementId:link.requirementId,assetId:link.assetId}}));}
  for(const run of records.extractionRuns||[]){const availableAt=latest(run.completedAt,artifactAvailability.get(run.artifactId));if(!availableAt||!atOrBefore(availableAt,cutoff))continue;runAvailability.set(run.id,availableAt);entries.push(entry({category:"extraction",event:"extraction_run_completed",occurredAt:run.startedAt,availableAt,recordType:"evidence_extraction_run",id:run.id,summary:`${run.extractorName} extraction ${run.status}`,status:run.status,contextId:run.contextId,subjectReferenceId:run.subjectReferenceId,details:{assetId:run.assetId,artifactId:run.artifactId,executionMode:run.executionMode,provider:run.provider,modelIdentifier:run.modelIdentifier,instructionReference:run.instructionReference,completedAt:iso(run.completedAt),errorCode:run.errorCode}}));}
  for(const input of records.runArtifacts||[]){const availableAt=runAvailability.get(input.extractionRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"lineage",event:"extraction_input_recorded",occurredAt:input.createdAt,availableAt,recordType:"evidence_extraction_run_artifact",id:`${input.extractionRunId}:${input.artifactId}:${input.inputRole}`,summary:`Extraction input recorded: ${input.inputRole}`,status:"recorded",details:{extractionRunId:input.extractionRunId,artifactId:input.artifactId,inputRole:input.inputRole}}));}
  for(const value of records.extractedValues||[]){const availableAt=runAvailability.get(value.extractionRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"fact",event:"deterministic_value_extracted",occurredAt:value.createdAt,availableAt,recordType:"evidence_extracted_value",id:value.id,summary:`Deterministic value: ${value.schemaFieldId} = ${factValue(value.extractedValue)}`,status:"recorded",details:{extractionRunId:value.extractionRunId,schemaFieldId:value.schemaFieldId,value:value.extractedValue}}));}
  for(const fact of records.facts||[]){const availableAt=runAvailability.get(fact.extractionRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"fact",event:"fact_recorded",occurredAt:fact.createdAt,availableAt,recordType:"evidence_fact",id:fact.id,summary:`Fact: ${fact.semanticConceptId} = ${factValue(fact.factValue)}`,status:fact.supportState,contextId:fact.contextId,subjectReferenceId:fact.subjectReferenceId,details:{extractionRunId:fact.extractionRunId,artifactId:fact.artifactId,informationNeedId:fact.informationNeedId,requestStatus:fact.requestStatus,groundingType:fact.groundingType,value:fact.factValue}}));}
  for(const support of records.supports||[]){const fact=facts.get(support.factId),availableAt=fact&&runAvailability.get(fact.extractionRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"support",event:"fact_artifact_support_recorded",occurredAt:support.createdAt,availableAt,recordType:"evidence_fact_artifact_support",id:`${support.factId}:${support.artifactId}`,summary:"Fact linked to supporting Artifact",status:"recorded",details:{factId:support.factId,artifactId:support.artifactId}}));}
  for(const locator of records.locators||[]){const fact=facts.get(locator.factId),availableAt=fact&&runAvailability.get(fact.extractionRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"support",event:"fact_locator_recorded",occurredAt:locator.createdAt,availableAt,recordType:"evidence_fact_artifact_locator",id:locator.id,summary:`${locator.locatorKind.toUpperCase()} support locator recorded`,status:"recorded",details:{factId:locator.factId,artifactId:locator.artifactId,ordinal:locator.locatorOrdinal,jsonPath:locator.jsonPath,domReference:locator.domReference,pageStart:locator.pageStart,pageEnd:locator.pageEnd,supportExcerpt:locator.supportExcerpt,supportDescription:locator.supportDescription,region:locator.region}}));}
  for(const relation of records.typedRelationships||[]){const fact=facts.get(relation.factId),availableAt=fact&&runAvailability.get(fact.extractionRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"relationship",event:"typed_relationship_recorded",occurredAt:relation.createdAt,availableAt,recordType:"evidence_fact_typed_relationship",id:relation.factId,summary:`${name(relation.subjectSnapshot)} → ${relation.relationshipType} → ${name(relation.objectSnapshot)}`,status:relation.temporalState,details:{factId:relation.factId,valueKind:relation.valueKind,measurementType:relation.measurementType,exactValue:relation.exactValue,qualitativeValue:relation.qualitativeValue,unit:relation.unit,sourceEffectiveDate:relation.sourceEffectiveDate}}));}
  for(const assertion of records.typedSetAssertions||[]){const fact=facts.get(assertion.factId),availableAt=fact&&runAvailability.get(fact.extractionRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"relationship",event:"typed_set_assertion_recorded",occurredAt:assertion.createdAt,availableAt,recordType:"evidence_fact_typed_set_assertion",id:assertion.factId,summary:`Set assertion: ${assertion.setConcept} is ${assertion.emptyState}`,status:assertion.completenessState,details:{factId:assertion.factId,explicitMemberCount:assertion.explicitMemberCount,temporalState:assertion.temporalState,sourceEffectiveDate:assertion.sourceEffectiveDate}}));}
  for(const derivation of records.derivations||[]){const fact=facts.get(derivation.derivedFactId),availableAt=fact&&runAvailability.get(fact.extractionRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"lineage",event:"fact_derivation_recorded",occurredAt:derivation.derivedAt,availableAt,recordType:"evidence_fact_derivation",id:`${derivation.derivedFactId}:${derivation.inputFactId}:${derivation.transformationId}`,summary:`Derived Fact created by ${derivation.transformationId}`,status:"recorded",details:{derivedFactId:derivation.derivedFactId,inputFactId:derivation.inputFactId,transformationVersion:derivation.transformationVersion,transformationReference:derivation.transformationReference}}));}
  for(const verification of records.verifications||[]){const availableAt=runAvailability.get(verification.verificationExtractionRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"verification",event:"independent_verification_recorded",occurredAt:verification.performedAt,availableAt,recordType:"evidence_verification_attempt",id:verification.id,summary:`Independent verification: ${verification.outcome}`,status:verification.outcome,details:{targetExtractionRunId:verification.targetExtractionRunId,targetFactId:verification.targetFactId,verificationExtractionRunId:verification.verificationExtractionRunId}}));}
  for(const operation of records.interpretationOperations||[]){if(!atOrBefore(operation.startedAt,cutoff))continue;const complete=operation.completedAt&&atOrBefore(operation.completedAt,cutoff),availableAt=complete?operation.completedAt:operation.startedAt;entries.push(entry({category:"interpretation",event:complete?"interpretation_operation_completed":"interpretation_operation_started",occurredAt:operation.startedAt,availableAt,recordType:"evidence_interpretation_operation",id:operation.id,summary:complete?`Targeted interpretation ${operation.status}`:"Targeted interpretation in progress",status:complete?operation.status:"in_progress",contextId:operation.contextId,details:{extractionRunId:complete?operation.extractionRunId:null,completedAt:complete?iso(operation.completedAt):null,failureCode:complete?operation.failureCode:null},limitations:complete?[]:["Later terminal result and failure details are intentionally hidden at this cutoff."]}));}
  for(const run of records.needEvaluationRuns||[]){const availableAt=run.completedAt;if(availableAt&&atOrBefore(availableAt,cutoff)){evaluationAvailability.set(run.id,iso(availableAt));entries.push(entry({category:"evaluation",event:"fact_need_evaluation_run_completed",occurredAt:run.evaluatedAt||run.startedAt,availableAt,recordType:"evidence_need_evaluation_run",id:run.id,summary:`Fact-to-Need evaluation ${run.status}`,status:run.status,contextId:run.contextId,subjectReferenceId:run.subjectReferenceId,details:{informationNeedId:run.informationNeedId,evaluationMethod:run.evaluationMethod,provider:run.provider,modelIdentifier:run.modelIdentifier,errorCode:run.errorCode}}));}}
  for(const evaluation of records.factNeedEvaluations||[]){const availableAt=evaluationAvailability.get(evaluation.evaluationRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"evaluation",event:"fact_need_evaluation_recorded",occurredAt:evaluation.createdAt,availableAt,recordType:"evidence_fact_need_evaluation",id:evaluation.id,summary:`Fact addresses Need: ${evaluation.result}`,status:evaluation.result,details:{evaluationRunId:evaluation.evaluationRunId,factId:evaluation.factId,reason:evaluation.reason,qualification:evaluation.qualification}}));}
  for(const assessment of records.coverageRuns||[]){const availableAt=latest(assessment.assessedAt,assessment.createdAt);if(availableAt&&atOrBefore(availableAt,cutoff)){assessmentAvailability.set(assessment.id,availableAt);entries.push(entry({category:"assessment",event:"coverage_assessment_recorded",occurredAt:assessment.assessedAt,availableAt,recordType:"evidence_coverage_assessment_run",id:assessment.id,summary:`Coverage ${assessment.coverageState}; completeness ${assessment.completenessState}`,status:assessment.coverageState,contextId:assessment.contextId,subjectReferenceId:assessment.subjectReferenceId,details:{informationNeedId:assessment.informationNeedId,disagreementState:assessment.disagreementState,temporalState:assessment.temporalState,emptySetState:assessment.emptySetState,inputSufficiency:assessment.inputSufficiency,reasonCodes:assessment.reasonCodes,limitations:assessment.limitations}}));}}
  for(const candidate of records.coverageCandidates||[]){const availableAt=assessmentAvailability.get(candidate.assessmentRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"assessment",event:"coverage_candidate_recorded",occurredAt:candidate.createdAt,availableAt,recordType:"evidence_coverage_assessment_candidate",id:candidate.id,summary:`Coverage candidate: ${candidate.contributionRole}`,status:candidate.evaluationResult,details:{assessmentRunId:candidate.assessmentRunId,a4aEvaluationId:candidate.a4aEvaluationId,factId:candidate.factId}}));}
  for(const finding of records.coverageFindings||[]){const availableAt=assessmentAvailability.get(finding.assessmentRunId);if(availableAt&&atOrBefore(availableAt,cutoff))entries.push(entry({category:"assessment",event:"coverage_comparison_recorded",occurredAt:finding.createdAt,availableAt,recordType:"evidence_coverage_comparison_finding",id:finding.id,summary:`Evidence comparison: ${finding.relationship}`,status:finding.relationship,details:{assessmentRunId:finding.assessmentRunId,factAId:finding.factAId,factBId:finding.factBId,comparable:finding.comparable,reasonCode:finding.reasonCode}}));}
  entries.sort((a,b)=>a.availableAt.localeCompare(b.availableAt)||a.occurredAt.localeCompare(b.occurredAt)||a.sourceRecordType.localeCompare(b.sourceRecordType)||a.evidenceReference.id.localeCompare(b.evidenceReference.id));return entries;
}

module.exports={AVAILABILITY_RULES_VERSION,AVAILABILITY_RULES,LIMITATIONS,projectEvidence};
